name: Link Validator

on:
  pull_request:
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  validate-links:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # See https://github.com/actions/checkout/issues/299#issuecomment-677674415
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 100

      # temporarily disable tag fetch (there are no tags right now and this then fails)
      # - name: Fetch tags
      #  run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: sbt site
        run: sbt docs/makeSite

      - name: Install Coursier command line tool
        run: curl -fLo cs https://git.io/coursier-cli-linux && chmod +x cs && ./cs

      - name: Run Link Validator
        run: ./cs launch net.runne::site-link-validator:0.2.0 -- scripts/link-validator.conf
