name: Publish

on:
  push:
    branches:
      - main
    tags: ["*"]

jobs:
  sbt:
    name: sbt publish
    runs-on: ubuntu-latest
    if: github.repository == 'apache/incubator-pekko-persistence-jdbc'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8    

      - name: Publish
        run: |-
        # cp .jvmopts-ci .jvmopts
          sbt +publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
